const products = [
    {
        _id: '1',
        name: 'Harry Potter and the Philosopher\'s Stone',
        author: 'JK Rowling',
        image: '/img/hp_1.jpg',
        description: "'He'll be famous – a legend – I wouldn't be surprised if today was known as Harry Potter Day in future – there will be books written about Harry' Minerva McGonagall.Strange things always seem to happen when Harry Potter is around. Things that unsettle his guardians, the Dursleys. They strongly disapprove of strangeness. It's only when a letter arrives, delivered by a shaggy giant of a man called Hagrid, that Harry learns the truth that will transform his entire future: his parents were killed by the evil Lord Voldemort, and he, Harry, is a wizard.\nWhisked away to Hogwarts School of Witchcraft and Wizardy, Harry discovers a world of enchantments, ghosts, Quidditch, and friends who will stand, through everything, by his side. But when Harry hears of a stone with great powers, he finds that his school has its own dark secrets – and an adventure that will become the stuff of legend begins.",
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 10,
        rating: 4.5,
        numReviews: 50
    },
    {
        _id: '2',
        name: 'Harry Potter and the Chamber of Secrets',
        author: 'JK Rowling',
        image: '/img/hp_2.jpg',
        description: 'The spellbinding first adventure in the Harry Potter series and Winner of Winners in the 2020 Blue Peter Book Awards - voted for by children to celebrate twenty years of Blue Peter\'s amazing prize. ',
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 10,
        rating: 4.5,
        numReviews: 50
    },
    {
        _id: '3',
        name: 'Harry Potter and the Prisoner of Azhkaben',
        author: 'JK Rowling',
        image: '/img/hp_3.jpg',
        description: 'The spellbinding first adventure in the Harry Potter series and Winner of Winners in the 2020 Blue Peter Book Awards - voted for by children to celebrate twenty years of Blue Peter\'s amazing prize. ',
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 10,
        rating: 4.5,
        numReviews: 50
    },
    {
        _id: '4',
        name: 'Harry Potter and the Goblet of Fire',
        author: 'JK Rowling',
        image: '/img/hp_4.jpg',
        description: 'The spellbinding first adventure in the Harry Potter series and Winner of Winners in the 2020 Blue Peter Book Awards - voted for by children to celebrate twenty years of Blue Peter\'s amazing prize. ',
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 10,
        rating: 4.5,
        numReviews: 50
    },{
        _id: '5',
        name: 'Harry Potter and the Order of Phoenix',
        author: 'JK Rowling',
        image: '/img/hp_5.jpg',
        description: 'The spellbinding first adventure in the Harry Potter series and Winner of Winners in the 2020 Blue Peter Book Awards - voted for by children to celebrate twenty years of Blue Peter\'s amazing prize. ',
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 10,
        rating: 4.5,
        numReviews: 50
    },
    {
        _id: '6',
        name: 'Harry Potter and the Half-Blood Prince',
        author: 'JK Rowling',
        image: '/img/hp_6.jpg',
        description: 'The spellbinding first adventure in the Harry Potter series and Winner of Winners in the 2020 Blue Peter Book Awards - voted for by children to celebrate twenty years of Blue Peter\'s amazing prize. ',
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 10,
        rating: 4.5,
        numReviews: 50
    },
    {
        _id: '7',
        name: 'Harry Potter and the Deathly Hallows',
        author: 'JK Rowling',
        image: '/img/hp_7.jpg',
        description: 'The spellbinding first adventure in the Harry Potter series and Winner of Winners in the 2020 Blue Peter Book Awards - voted for by children to celebrate twenty years of Blue Peter\'s amazing prize. ',
        publisher: 'Bloomsbury In.',
        genre: 'Children Fantasy',
        format: 'Paperback',
        pages: 352,
        price: 499,
        countInStock : 0,
        rating: 4.5,
        numReviews: 50
    }
]
export default products;